---
-  hosts: web
   tasks:
    - name: Install Apache
      apt:
        name: apache2
        state: latest
    - name: start Apache
      service:
        name: apache2
        state: started

-  hosts: web
   tasks:
    - namme: Install fail2ban
      apt:
        name: fail2ban
        state: latest
      
      
